
project_id = "cfbleqfvxyosenezksbc"

[create-checkout-session]
verify_jwt = true

[check-subscription]
verify_jwt = true

[generate-blog-ideas]
verify_jwt = false

[generate-blog]
verify_jwt = false

[auto-generate-blog]
verify_jwt = true

[create-blog-automation-schedule]
verify_jwt = true

[run-scheduled-blogs]
verify_jwt = false

[generate-blog-image]
verify_jwt = false
