
# This configuration file is a TOML file that specifies authentication information required for
# local development and testing purposes.

[global.env]
SUPABASE_URL = "env"
SUPABASE_SERVICE_ROLE_KEY = "env"
OPENAI_API_KEY = "env"
